"""
DeerFlow-X LangGraph Workflow Engine
多项目并发 Agent 调度核心
使用硅基流动 SiliconFlow API（兼容 OpenAI 格式）
"""
from __future__ import annotations

import os
import asyncio
import uuid
import logging
from datetime import datetime
from typing import TypedDict, Annotated, Literal, Optional
from collections import defaultdict

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import Interrupt
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# 硅基流动 API 配置
SILICONFLOW_API_KEY = os.getenv("OPENAI_API_KEY", "sk-pvqbgxpyqojhhibldeycmhohogdipzxkoswtsgpcixrftutj")
SILICONFLOW_BASE_URL = "https://api.siliconflow.cn/v1"

# 模型分层策略
MODEL_LIGHT = "deepseek-ai/DeepSeek-V3.2"  # ¥2/M in / ¥3/M out — 简单任务
MODEL_PRO = "deepseek-ai/DeepSeek-V3"      # ¥2/M in / ¥8/M out — 复杂Agent任务
MODEL_MAX = "deepseek-ai/DeepSeek-R1"     # ¥2/M in / ¥8/M out — 深度推理

# ─── State 定义 ────────────────────────────────────────────────────────────────


class AgentRoleLiteral(str):
    CEO = "ceo"
    ARCHITECT = "architect"
    RESEARCHER = "researcher"
    WRITER = "writer"
    CODER = "coder"
    REVIEWER = "reviewer"
    TESTER = "tester"
    DEVOPS = "devops"
    PRODUCT_MANAGER = "pm"
    BRAINSTORMER = "brainstormer"


class AgentMessage(BaseModel):
    """Agent 之间传递的消息"""
    from_agent: str
    to_agent: str | None = None  # None = broadcast
    content: str
    attachments: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class GraphState(TypedDict, total=False):
    """LangGraph 全局状态"""
    project_id: str
    task: str
    task_id: str
    current_agent: str
    next_agent: str | None
    results: dict
    errors: list[dict]
    iteration: int
    max_iterations: int
    messages: list[AgentMessage]
    context: dict
    output: str | None
    status: Literal["pending", "running", "completed", "failed"]


# ─── Agent 节点函数 ────────────────────────────────────────────────────────────


async def orchestrator_node(state: GraphState) -> dict:
    """任务分解节点 — CEO 角色（使用 MODEL_PRO）"""
    task = state.get("task", "")
    iteration = state.get("iteration", 0)

    logger.info(f"[orchestrator] 分解任务（模型={MODEL_PRO}）: {task[:50]}... (iter={iteration})")

    # 简单规则：根据关键词决定下一个 agent
    task_lower = task.lower()
    if any(k in task_lower for k in ["写", "code", "代码", "implement", "build"]):
        next_agent = AgentRoleLiteral.CODER
    elif any(k in task_lower for k in ["研究", "research", "搜索", "调研"]):
        next_agent = AgentRoleLiteral.RESEARCHER
    elif any(k in task_lower for k in ["写文章", "文档", "doc", "content"]):
        next_agent = AgentRoleLiteral.WRITER
    elif any(k in task_lower for k in ["review", "review", "审查", "检查"]):
        next_agent = AgentRoleLiteral.REVIEWER
    else:
        next_agent = AgentRoleLiteral.CODER  # 默认走 coder

    return {
        "current_agent": AgentRoleLiteral.CEO,
        "next_agent": next_agent,
        "iteration": iteration + 1,
    }


async def researcher_node(state: GraphState) -> dict:
    """研究节点 — 搜集信息"""
    task = state.get("task", "")
    logger.info(f"[researcher] 研究任务: {task[:50]}...")

    # 模拟研究结果
    result = {
        "findings": [
            f"研究结果1: 关于{task[:30]}的相关资料",
            f"研究结果2: 竞品分析资料",
            f"研究结果3: 技术选型建议",
        ],
        "summary": f"已完成对'{task}'的初步研究，共发现3个关键点。",
    }

    messages = state.get("messages", []) + [
        AgentMessage(from_agent=AgentRoleLiteral.RESEARCHER, content=result["summary"])
    ]

    return {
        "current_agent": AgentRoleLiteral.RESEARCHER,
        "next_agent": AgentRoleLiteral.CODER,
        "results": {**state.get("results", {}), "research": result},
        "messages": messages,
    }


async def coder_node(state: GraphState) -> dict:
    """编码节点 — 核心开发"""
    task = state.get("task", "")
    iteration = state.get("iteration", 0)
    logger.info(f"[coder] 执行任务: {task[:50]}... (iter={iteration})")

    result = {
        "files_created": [
            f"/workspace/deer-flow-x/generated/{uuid.uuid4().hex[:8]}_main.py",
            f"/workspace/deer-flow-x/generated/{uuid.uuid4().hex[:8]}_utils.py",
        ],
        "code": f"# Auto-generated by DeerFlow-X Coder Agent\n# Task: {task}\n# Timestamp: {datetime.utcnow().isoformat()}\n\nclass GeneratedCode:\n    pass",
        "lines": 50 + iteration * 10,
    }

    messages = state.get("messages", []) + [
        AgentMessage(from_agent=AgentRoleLiteral.CODER, content=f"代码生成完成: {result['lines']}行")
    ]

    return {
        "current_agent": AgentRoleLiteral.CODER,
        "next_agent": AgentRoleLiteral.REVIEWER,
        "results": {**state.get("results", {}), "code": result},
        "messages": messages,
    }


async def writer_node(state: GraphState) -> dict:
    """写作节点 — 文档/内容生成"""
    task = state.get("task", "")
    logger.info(f"[writer] 写作任务: {task[:50]}...")

    result = {
        "document": f"# {task}\n\nGenerated by DeerFlow-X Writer Agent\n\n## 概述\n\n本文档由 AI 自动生成。",
        "word_count": 500,
    }

    messages = state.get("messages", []) + [
        AgentMessage(from_agent=AgentRoleLiteral.WRITER, content=f"文档生成完成: {result['word_count']}字")
    ]

    return {
        "current_agent": AgentRoleLiteral.WRITER,
        "next_agent": AgentRoleLiteral.REVIEWER,
        "results": {**state.get("results", {}), "document": result},
        "messages": messages,
    }


async def reviewer_node(state: GraphState) -> dict:
    """审核节点 — 质量把关"""
    results = state.get("results", {})
    logger.info(f"[reviewer] 审核结果...")

    # 检查是否有代码或文档
    has_code = "code" in results
    has_document = "document" in results

    review_result = {
        "approved": has_code or has_document,
        "issues": [],
        "score": 0,
    }

    if has_code:
        code_result = results["code"]
        if code_result.get("lines", 0) > 0:
            review_result["score"] = min(10, 6 + code_result["lines"] // 20)
            review_result["issues"].append(f"代码{code_result['lines']}行，评分{review_result['score']}/10")

    if has_document:
        review_result["approved"] = True
        review_result["issues"].append("文档质量达标")

    messages = state.get("messages", []) + [
        AgentMessage(
            from_agent=AgentRoleLiteral.REVIEWER,
            content=f"审核完成: {'通过' if review_result['approved'] else '需修改'} — {', '.join(review_result['issues'])}"
        )
    ]

    return {
        "current_agent": AgentRoleLiteral.REVIEWER,
        "next_agent": None if review_result["approved"] else AgentRoleLiteral.CODER,
        "results": {**results, "review": review_result},
        "messages": messages,
        "output": f"最终产出: {review_result['issues']}",
    }


# ─── 边定义 ───────────────────────────────────────────────────────────────────


def should_continue(state: GraphState) -> Literal["continue", "end"]:
    """条件边：决定是否继续迭代"""
    max_iter = state.get("max_iterations", 10)
    iteration = state.get("iteration", 0)
    status = state.get("status", "pending")
    next_agent = state.get("next_agent")

    if status == "completed":
        return "end"

    if iteration >= max_iter:
        logger.warning(f"[workflow] 达到最大迭代次数 {max_iter}，强制结束")
        return "end"

    if next_agent is None:
        return "end"

    return "continue"


def route_to_agent(state: GraphState) -> str:
    """根据 next_agent 字段路由到对应节点"""
    agent_map = {
        AgentRoleLiteral.CEO: "orchestrator",
        AgentRoleLiteral.RESEARCHER: "researcher",
        AgentRoleLiteral.CODER: "coder",
        AgentRoleLiteral.WRITER: "writer",
        AgentRoleLiteral.REVIEWER: "reviewer",
    }
    next_agent = state.get("next_agent", AgentRoleLiteral.CODER)
    node = agent_map.get(next_agent, "coder")
    logger.info(f"[route] → {node}")
    return node


# ─── Workflow Builder ──────────────────────────────────────────────────────────


def build_workflow() -> StateGraph:
    """构建 LangGraph 工作流"""
    workflow = StateGraph(GraphState)

    # 注册节点
    workflow.add_node("orchestrator", orchestrator_node)
    workflow.add_node("researcher", researcher_node)
    workflow.add_node("coder", coder_node)
    workflow.add_node("writer", writer_node)
    workflow.add_node("reviewer", reviewer_node)

    # 设置入口
    workflow.set_entry_point("orchestrator")

    # 普通边
    workflow.add_edge("orchestrator", route_to_agent)
    workflow.add_edge("researcher", "coder")
    workflow.add_edge("writer", "reviewer")

    # 条件边：coder → [reviewer | coder(重试)]
    workflow.add_conditional_edges(
        "reviewer",
        should_continue,
        {
            "continue": route_to_agent,  # 路由回 coder
            "end": END,
        }
    )

    # coder 完成后来 reviewer
    workflow.add_edge("coder", "reviewer")

    return workflow


# ─── 多项目并发管理器 ─────────────────────────────────────────────────────────


class WorkflowManager:
    """
    多项目并发调度器
    每个项目有独立的 graph + checkpointer
    """

    def __init__(self):
        self.graphs: dict[str, StateGraph] = {}
        self.compiled: dict[str, object] = {}
        self.checkpointers: dict[str, MemorySaver] = {}
        self.running_tasks: dict[str, asyncio.Task] = {}
        self._lock = asyncio.Lock()

    def _get_or_create_graph(self, project_id: str) -> StateGraph:
        if project_id not in self.graphs:
            self.graphs[project_id] = build_workflow()
            self.checkpointers[project_id] = MemorySaver()
            self.compiled[project_id] = self.graphs[project_id].compile(
                checkpointer=self.checkpointers[project_id]
            )
            logger.info(f"[manager] 为项目 {project_id} 创建新 workflow")
        return self.compiled[project_id]

    async def run_task(
        self,
        project_id: str,
        task: str,
        task_id: str | None = None,
        max_iterations: int = 10,
    ) -> dict:
        """为指定项目运行任务"""
        async with self._lock:
            compiled = self._get_or_create_graph(project_id)

        initial_state: GraphState = {
            "project_id": project_id,
            "task": task,
            "task_id": task_id or str(uuid.uuid4()),
            "current_agent": AgentRoleLiteral.CEO,
            "next_agent": AgentRoleLiteral.CODER,
            "results": {},
            "errors": [],
            "iteration": 0,
            "max_iterations": max_iterations,
            "messages": [],
            "context": {},
            "output": None,
            "status": "running",
        }

        config = {
            "configurable": {
                "thread_id": f"{project_id}-{task_id or uuid.uuid4().hex}",
            }
        }

        try:
            logger.info(f"[manager] 启动任务 {task_id} for project {project_id}")
            final_state = await compiled.ainvoke(initial_state, config)

            output = final_state.get("output") or final_state.get("results", {})
            logger.info(f"[manager] 任务 {task_id} 完成: {output}")

            return {
                "status": "completed",
                "project_id": project_id,
                "task_id": task_id,
                "results": final_state.get("results", {}),
                "messages": final_state.get("messages", []),
                "output": output,
            }

        except Exception as e:
            logger.exception(f"[manager] 任务 {task_id} 失败: {e}")
            return {
                "status": "failed",
                "project_id": project_id,
                "task_id": task_id,
                "error": str(e),
            }

    async def run_task_background(
        self,
        project_id: str,
        task: str,
        task_id: str | None = None,
        max_iterations: int = 10,
    ) -> str:
        """后台运行任务，返回 task_id"""
        tid = task_id or str(uuid.uuid4())
        coro = self.run_task(project_id, task, tid, max_iterations)
        self.running_tasks[tid] = asyncio.create_task(coro)
        logger.info(f"[manager] 后台任务 {tid} 已启动")
        return tid

    async def get_task_result(self, task_id: str, timeout: float = 0) -> dict | None:
        """获取后台任务结果"""
        task = self.running_tasks.get(task_id)
        if task is None:
            return None

        if timeout <= 0:
            try:
                return task.result()
            except asyncio.InvalidStateError:
                return None

        try:
            return await asyncio.wait_for(task, timeout=timeout)
        except asyncio.TimeoutError:
            return {"status": "running", "task_id": task_id}


# ─── Scheduler（API 层暴露的调度器）───────────────────────────────────────────


class Scheduler:
    """
    调度器：API 层调用的入口，封装 WorkflowManager。
    提供 start/stop/is_running/get_state 等项目管理方法。
    """

    def __init__(self):
        self._manager = workflow_manager
        self._running_projects: set[str] = set()
        self._workflow_states: dict[str, dict] = {}

    def get_running_projects(self) -> list[str]:
        return list(self._running_projects)

    def is_project_running(self, project_id: str) -> bool:
        return project_id in self._running_projects

    def get_workflow_state(self, project_id: str) -> dict | None:
        return self._workflow_states.get(project_id)

    async def start_project_workflow(self, project_id: str):
        """启动项目主工作流（后台执行）"""
        if project_id in self._running_projects:
            return
        self._running_projects.add(project_id)
        self._workflow_states[project_id] = {"step": 0, "status": "running"}
        logger.info(f"[scheduler] 启动项目 {project_id} 工作流")
        # 异步运行主任务（placeholder: 后续接真实任务队列）
        async def _run():
            from ..core.in_memory_store import store
            project = store.get_project(project_id)
            if not project:
                self._running_projects.discard(project_id)
                return
            for task in store.list_tasks(project_id=project_id):
                await self._manager.run_task(project_id, task.title, task.id)
            self._running_projects.discard(project_id)
            self._workflow_states[project_id] = {"step": 0, "status": "stopped"}
        asyncio.create_task(_run())

    async def stop_project_workflow(self, project_id: str) -> bool:
        """停止项目工作流"""
        if project_id not in self._running_projects:
            return False
        self._running_projects.discard(project_id)
        self._workflow_states[project_id] = {"step": 0, "status": "stopped"}
        logger.info(f"[scheduler] 停止项目 {project_id} 工作流")
        return True


# 全局单例（注意顺序：workflow_manager 必须先于 scheduler 实例化）
workflow_manager = WorkflowManager()
scheduler = Scheduler()
